package com.docker1.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docker..user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docker..user.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docker..user.loginTime
     *
     * @mbg.generated
     */
    private Integer logintime;

    public User(String id, String ip, Integer logintime) {
        this.id = id;
        this.ip = ip;
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docker..user.id
     *
     * @return the value of docker..user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docker..user.id
     *
     * @param id the value for docker..user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docker..user.ip
     *
     * @return the value of docker..user.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docker..user.ip
     *
     * @param ip the value for docker..user.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docker..user.loginTime
     *
     * @return the value of docker..user.loginTime
     *
     * @mbg.generated
     */
    public Integer getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docker..user.loginTime
     *
     * @param logintime the value for docker..user.loginTime
     *
     * @mbg.generated
     */
    public void setLogintime(Integer logintime) {
        this.logintime = logintime;
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", ip='" + ip + '\'' +
                ", logintime=" + logintime +
                '}';
    }
}